// @ts-check

/**
 * palette/index.js - the ONLY entry point to the color generator.
 *
 * Everything under engine/ is vendored from rampkit (see NOTICE.md) and must
 * never be imported directly by the CLI. This module:
 *
 *   1. runs the rampkit engine (hex -> full palette data)
 *   2. renders it with the chosen preset + color format
 *   3. re-wraps the output in the template's dark mode structure
 *      (prefers-color-scheme auto + [data-theme] manual override)
 *   4. appends the "app bridge" tokens that base.css and app CSS consume,
 *      so the app works unchanged with every preset/format combination
 */

import { generatePalette } from "./engine/generatePalette.js";
import { generateExportCode } from "./engine/export-formats.js";
import { isValidHex } from "./engine/color-utils.js";

/** CLI-facing names -> engine enums */
export const PRESETS = /** @type {const} */ ({
  shadcn: "shadcn",
  radix: "radix",
  "css-variables": "css-variables",
});

export const FORMATS = /** @type {const} */ ({
  hex: "HEX",
  rgb: "RGB",
  hsl: "HSL",
  "hsl-values": "HSL_VALUES",
  oklab: "OKLAB",
  oklch: "OKLCH",
});

export const SCHEMES = ["analogous", "monochromatic", "complementary", "triadic"];

export const DEFAULT_HEX = "#4DA0FF"; // hsl(212 100% 65%) - Larsen Utvikling brand blue

export { isValidHex };

/**
 * CSS usage idioms for the chosen color format - used in the generated
 * AGENTS.md/DESIGN.md so docs always match the palette architecture.
 * @param {keyof typeof FORMATS} format
 */
export function usageIdioms(format) {
  if (format === "hsl-values") {
    return {
      idiom: "hsl(var(--token))",
      alphaIdiom: "hsl(var(--token) / 0.75)",
    };
  }
  return {
    idiom: "var(--token)",
    alphaIdiom: "color-mix(in srgb, var(--token) 75%, transparent)",
  };
}

/** @param {string} hex */
export function normalizeHex(hex) {
  const clean = hex.trim().replace(/^#/, "").toUpperCase();
  return `#${clean.length === 3 ? clean.split("").map((c) => c + c).join("") : clean}`;
}

/**
 * Bridge token sources per preset. The bridge gives the app a stable, tiny
 * token surface (--surface, --on-surface, ...) regardless of which variables
 * the chosen preset emits.
 */
const BRIDGE_SOURCES = {
  shadcn: {
    surface: "background",
    "on-surface": "foreground",
    "surface-muted": "muted",
    "accent-solid": "accent-9",
    "accent-soft": "accent-3",
    line: "border",
  },
  radix: {
    surface: "gray-1",
    "on-surface": "gray-12",
    "surface-muted": "gray-2",
    "accent-solid": "accent-9",
    "accent-soft": "accent-3",
    line: "gray-6",
  },
};
BRIDGE_SOURCES["css-variables"] = BRIDGE_SOURCES.radix;

/**
 * @param {object} opts
 * @param {string} opts.hex - seed color, with or without leading '#'
 * @param {keyof typeof PRESETS} [opts.preset]
 * @param {keyof typeof FORMATS} [opts.format]
 * @param {string} [opts.scheme]
 * @returns {string} complete theme.css content
 */
export function generateThemeCss({
  hex,
  preset = "shadcn",
  format = "hsl-values",
  scheme = "analogous",
}) {
  if (!isValidHex(hex)) {
    throw new Error(`Invalid HEX color: "${hex}" (expected e.g. 4DA0FF or #4DA0FF)`);
  }
  if (!(preset in PRESETS)) {
    throw new Error(`Unknown preset: "${preset}" (expected ${Object.keys(PRESETS).join(" | ")})`);
  }
  if (!(format in FORMATS)) {
    throw new Error(`Unknown format: "${format}" (expected ${Object.keys(FORMATS).join(" | ")})`);
  }
  if (!SCHEMES.includes(scheme)) {
    throw new Error(`Unknown scheme: "${scheme}" (expected ${SCHEMES.join(" | ")})`);
  }

  const seed = normalizeHex(hex);
  const data = generatePalette({ hex: seed, scheme });
  const raw = generateExportCode(data, { preset, format: FORMATS[format] });
  const { light, dark } = extractBlocks(raw);

  const wrap = format === "hsl-values" ? (v) => `hsl(var(--${v}))` : (v) => `var(--${v})`;
  const bridge = Object.entries(BRIDGE_SOURCES[preset])
    .map(([name, source]) => `  --${name}: ${wrap(source)};`)
    .join("\n");

  return `/**
 * theme.css - color tokens
 *
 * Generated by @larsen-utvikling/create-next-app (rampkit engine).
 * Seed: ${seed} | preset: ${preset} | format: ${format} | scheme: ${scheme}
 *
 * Dark mode follows the OS automatically. Set data-theme="light" or
 * data-theme="dark" on <html> to override manually - no JS shipped.
 * Regenerate any time by re-running the scaffolder, or edit values freely.
 */

:root {
${indent(light, 2)}
}

@media (prefers-color-scheme: dark) {
  :root {
${indent(dark, 4)}
  }
}

[data-theme="light"] {
${indent(light, 2)}
}

[data-theme="dark"] {
${indent(dark, 2)}
}

/**
 * App bridge - the stable token surface consumed by base.css and app CSS.
 * These six names always exist, independent of preset and color format.
 */
:root {
${bridge}
}
`;
}

/**
 * Split the engine's output (":root { ... } @media (dark) { :root { ... } }")
 * into the light and dark declaration lists.
 * @param {string} css
 */
function extractBlocks(css) {
  const mediaIdx = css.indexOf("@media (prefers-color-scheme: dark)");
  if (mediaIdx === -1) {
    throw new Error("Unexpected engine output: missing dark mode block");
  }
  const light = innerBlock(css.slice(0, mediaIdx));
  const darkPart = css.slice(mediaIdx);
  const light2 = darkPart.indexOf(":root");
  const dark = innerBlock(darkPart.slice(light2));
  return { light, dark };
}

/** Extract the contents of the first balanced { ... } block. @param {string} str */
function innerBlock(str) {
  const open = str.indexOf("{");
  if (open === -1) throw new Error("Unexpected engine output: no block found");
  let depth = 0;
  for (let i = open; i < str.length; i++) {
    if (str[i] === "{") depth++;
    else if (str[i] === "}") {
      depth--;
      if (depth === 0) return str.slice(open + 1, i);
    }
  }
  throw new Error("Unexpected engine output: unbalanced braces");
}

/** Normalize indentation of a declaration block. @param {string} block @param {number} spaces */
function indent(block, spaces) {
  const pad = " ".repeat(spaces);
  return block
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => pad + line)
    .join("\n");
}
